version: '3.8'

services:
  # Database PostgreSQL per sviluppo
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: fintrack_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Server per sviluppo
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/fintrack_dev"
      JWT_SECRET: "dev-secret-key"
      PORT: 4000
      ALLOW_DEMO_SEED: "true"
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    depends_on:
      postgres:
        condition: service_healthy

  # Client per sviluppo
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    environment:
      VITE_API_URL: "http://localhost:4000"

volumes:
  postgres_dev_data:
