version: '3.8'

services:
  # Database PostgreSQL
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: fintrack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # App FinTrack
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/fintrack"
      JWT_SECRET: "your-super-secret-jwt-key"
      PORT: 4000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./server/prisma:/app/server/prisma

volumes:
  postgres_data:
