services:
  #################
  # Backend (Sviluppo)
  #################
  app-dev:
    container_name: fintrack-dev-app
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@fintrack-prod-db:5432/${POSTGRES_DB}?schema=public
    volumes:
      # Hot-reloading: collega il tuo codice locale al container
      - ./server:/app/server
      # Volume "anonimo" per node_modules per evitare conflitti
      - /app/server/node_modules
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"
    networks:
      - fintrack-prod
      - default-dev
    restart: unless-stopped

  #################
  # Frontend (Sviluppo)
  #################
  client-dev:
    container_name: fintrack-dev-client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      # Hot-reloading: collega il tuo codice locale al container
      - ./client:/app/client
      # Volume "anonimo" per node_modules
      - /app/client/node_modules
    depends_on:
      - app-dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - BACKEND_SERVICE_NAME=app-dev
    networks:
      - web-proxy
      - default-dev

networks:
  web-proxy:
    external: true
  fintrack-prod:
    external: true
    name: fintrack_fintrack-prod
  default-dev:
    driver: bridge
