# Build Stage
FROM node:22-slim AS builder
WORKDIR /app

# Installa openssl per Prisma
RUN apt-get update -y && apt-get install -y openssl

COPY server/package*.json ./
COPY server/prisma ./prisma/
RUN npm install
COPY server/ .
RUN npx prisma generate
RUN npm run build

# Production Stage
FROM node:22-slim
WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma

EXPOSE 4000
CMD ["npm", "run", "start"]
